services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - omnia_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:cached
      - ./public:/app/public:cached
      - ./prisma:/app/prisma:cached
      # Mount config files
      - ./next.config.ts:/app/next.config.ts:cached
      - ./tailwind.config.ts:/app/tailwind.config.ts:cached
      - ./tsconfig.json:/app/tsconfig.json:cached
      - ./postcss.config.mjs:/app/postcss.config.mjs:cached
      # Exclude node_modules and .next from mount (use container's versions)
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      # Google Calendar OAuth
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL:-http://localhost:3000}
      # Google Calendar API (Service Account)
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${GOOGLE_SERVICE_ACCOUNT_EMAIL:-}
      GOOGLE_PRIVATE_KEY: ${GOOGLE_PRIVATE_KEY:-}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID:-primary}
      # Twilio WhatsApp API
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-}
      TWILIO_WHATSAPP_NUMBER: ${TWILIO_WHATSAPP_NUMBER:-}
    depends_on:
      - db
    networks:
      - omnia_network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./public
          target: /app/public
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./next.config.ts
        - action: rebuild
          path: ./tailwind.config.ts

volumes:
  postgres_data:

networks:
  omnia_network:
    driver: bridge
